# Master Project Config
project_name: "Audio-Based-Threat-Detection"

# Audio Settings (Optimized for PANNs)
audio:
  sample_rate: 32000
  n_fft: 1024
  hop_length: 320
  n_mels: 64
  top_db: 80

# --- DATASET PATHS (COLAB READY) ---
paths:
  # Path from your Morning KaggleHub download
  vsd_root: "/root/.cache/kagglehub/datasets/fangfangz/audio-based-violence-detection-dataset/versions/3"
  vsd_excel: "/root/.cache/kagglehub/datasets/fangfangz/audio-based-violence-detection-dataset/versions/3/VSD.xlsx"
  vsd_audio_dir: "/root/.cache/kagglehub/datasets/fangfangz/audio-based-violence-detection-dataset/versions/3/audios_VSD/audios_VSD"
  
  # Persistent storage in Google Drive
  drive_project_root: "/content/drive/MyDrive/Research_Project"
  checkpoint_dir: "/content/drive/MyDrive/Research_Project/checkpoints"
  logs_dir: "/content/drive/MyDrive/Research_Project/logs"

# Training Hyperparameters
training:
  batch_size: 16
  learning_rate: 0.0001
  epochs: 50
